name: dermai
description: A Flutter application for dermatology AI analysis using YOLO models.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  camera: ^0.10.5
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1

  image: ^4.1.3
  google_fonts: ^6.3.1
  fl_chart: ^1.1.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  cloud_functions: 6.0.4
  googleapis: ^13.1.0
  googleapis_auth: ^2.0.0
  uuid: ^4.5.1
  intl: ^0.20.2
  dotted_border: ^3.1.0
  image_picker: ^1.2.0
  firebase_storage: ^13.0.2
  tflite_flutter: ^0.11.0
  foundation: ^0.0.5
  pdf: ^3.11.3
  printing: ^5.14.2
  audioplayers: ^6.0.0
  flutter_local_notifications: ^17.2.1
  path: ^1.9.1
  table_calendar: ^3.2.0
  file_picker: ^10.3.3
  url_launcher: ^6.3.2
  open_file: ^3.5.10
  shimmer: ^3.0.0
  firebase_app_check: ^0.4.1+2
  emailjs: ^1.0.0
  mailer: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/default_avatar.png
    - assets/models/
    - assets/models/SkinDisease.tflite
    - assets/models/diseaseLabels.txt
    - assets/models/SkinType.tflite
    - assets/models/skinTypeLabels.txt
    - assets/fonts/
    - assets/sounds/
    - assets/locations.json
    - assets/models/SkinDiseaseV3.tflite
    - assets/models/diseaseLabelsV3.txt

  fonts:
    - family: MaterialSymbolsOutlined
      fonts:
        - asset: assets/fonts/MaterialSymbolsOutlined-Regular.ttf
